//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WorkflowFormMaster
    {
        public int ID { get; set; }
        public int FM_PKID { get; set; }
        public string FM_FormCode { get; set; }
        public string FM_FormName { get; set; }
        public Nullable<int> FM_WorkflowTime { get; set; }
        public string FM_FormPath { get; set; }
        public string FM_Notes { get; set; }
        public Nullable<int> FM_Crby { get; set; }
        public Nullable<System.DateTime> FM_CrOn { get; set; }
        public string FM_Status { get; set; }
    }
}
