//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_WorkflowTransMasters
    {
        public int ID { get; set; }
        public int WTM_MasID { get; set; }
        public Nullable<int> WTM_WorkFlowID { get; set; }
        public Nullable<int> WTM_DOCID { get; set; }
        public string WTM_FormCode { get; set; }
        public string WTM_Subject { get; set; }
        public Nullable<int> WTM_AttachID { get; set; }
        public Nullable<int> WTM_CrBy { get; set; }
        public Nullable<int> WTM_IsDisposed { get; set; }
        public Nullable<int> WTM_DisposedBy { get; set; }
        public Nullable<int> WTM_WFProcessID { get; set; }
        public string WTM_Status { get; set; }
    }
}
