//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMaster
    {
        public int ID { get; set; }
        public string CID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FromName { get; set; }
        public string FromId { get; set; }
        public string ToName { get; set; }
        public string ToId { get; set; }
        public Nullable<bool> IsOpened { get; set; }
    }
}
