//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyMaster
    {
        public int ID { get; set; }
        public Nullable<int> UserUID { get; set; }
        public string FacultyName { get; set; }
        public string Qualification { get; set; }
        public string DateOfBirth { get; set; }
        public string EmailId { get; set; }
        public string ContactNo { get; set; }
        public string Experience { get; set; }
        public string Skills { get; set; }
        public string Languages { get; set; }
        public string Interests { get; set; }
        public byte[] ProfilePicture { get; set; }
        public bool IsEnabled { get; set; }
    }
}
