//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveUpdateCountDetail
    {
        public int LeaveCountID { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<System.DateTime> LeaveUpdatedDate { get; set; }
        public string NoOfDays { get; set; }
    }
}
