//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveHistoryMaster
    {
        public int LeaveHistoryMasterID { get; set; }
        public Nullable<int> LeaveTypeID { get; set; }
        public string TotalLeaveTaken { get; set; }
        public string TotalLeaveRemaining { get; set; }
        public Nullable<System.DateTime> LeaveStartingDate { get; set; }
        public Nullable<System.DateTime> LeaveEndingDate { get; set; }
        public string LeaveMonthlyDetails { get; set; }
        public string LeaveCount { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string LeaveCredited { get; set; }
        public string LeaveDebited { get; set; }
    
        public virtual LeaveMaster LeaveMaster { get; set; }
    }
}
