//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudetTestPaperResult
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string TestPaperId { get; set; }
        public string TestPaperName { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public string GradeObtained { get; set; }
        public bool IsEnable { get; set; }
    }
}
