//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTest
    {
        public string ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string TestName { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public string GradeObtained { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    }
}
