//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDocumentDetail
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> FileId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string DocumentName { get; set; }
        public byte[] Documents { get; set; }
        public string DocumentType { get; set; }
        public string DocumentSize { get; set; }
    }
}
