//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsTest
    {
        public int ID { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public string GradeObtained { get; set; }
        public bool IsEnable { get; set; }
        public string Level { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> TechnologyId { get; set; }
    }
}
