//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentImage
    {
        public int ID { get; set; }
        public Nullable<int> StudentUID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public byte[] Documents { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsEnabled { get; set; }
    }
}
