//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCartDetail
    {
        public int ID { get; set; }
        public Nullable<int> Domain { get; set; }
        public Nullable<int> Technology { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Price { get; set; }
    }
}
