//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentCours
    {
        public int ID { get; set; }
        public string StudentId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public bool CompletionStatus { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public Nullable<int> TechnologyId { get; set; }
        public Nullable<int> DomainId { get; set; }
        public bool IsDefault { get; set; }
    }
}
