//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentDetail
    {
        public int ID { get; set; }
        public string StudentUID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> Qualification { get; set; }
        public Nullable<int> Occupation { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public bool IsEnabled { get; set; }
        public string StreetAddress { get; set; }
        public string CityAddress { get; set; }
    }
}
