//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTechnologyMaster
    {
        public int ID { get; set; }
        public string TechnologyName { get; set; }
        public Nullable<int> Domain { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<int> Assignments { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> Duration { get; set; }
        public byte[] Images { get; set; }
    }
}
