//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaperName
    {
        public int Id { get; set; }
        public string TestPaperId { get; set; }
        public string TPName { get; set; }
        public string Standard { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
