//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestPaper
    {
        public int Id { get; set; }
        public string TestPaperId { get; set; }
        public string TestPaperName { get; set; }
        public string Time { get; set; }
        public Nullable<int> DomainId { get; set; }
        public Nullable<int> TechnologyId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> ChapterId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsSaved { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
