//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionTable
    {
        public int ID { get; set; }
        public string Amount { get; set; }
        public string TransactionId { get; set; }
        public string TransactionStatus { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Hash { get; set; }
    }
}
