//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDocument
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string UploadType { get; set; }
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public string DocumentSize { get; set; }
        public byte[] Documents { get; set; }
        public string Comments { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public Nullable<int> TechnologyID { get; set; }
    }
}
