//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class useractivity
    {
        public int OnlineID { get; set; }
        public string UserID { get; set; }
        public string ConnectionID { get; set; }
        public string Status { get; set; }
        public string Avatar { get; set; }
    }
}
