//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VA_Workflow_Leave_Master
    {
        public int Id { get; set; }
        public int MasID { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public string LeaveApplicationNo { get; set; }
        public Nullable<int> OpeningBalance { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<int> LeaveTaken { get; set; }
        public Nullable<int> ClosingBalance { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<System.DateTime> LeaveAppliedDate { get; set; }
        public string From_User { get; set; }
        public string To_User { get; set; }
        public string FormCode { get; set; }
        public string LeaveSubject { get; set; }
        public string CreatedUser { get; set; }
        public string Trans_ID { get; set; }
        public Nullable<bool> Approvalone { get; set; }
        public Nullable<bool> Approvaltwo { get; set; }
        public Nullable<bool> Approvalthree { get; set; }
        public string ApprovaloneDate { get; set; }
        public string ApprovaltwoDate { get; set; }
        public string ApprovalthreeDate { get; set; }
        public string LastUpdatedDate { get; set; }
        public string LeavePurpose { get; set; }
        public string ContactNumber { get; set; }
    }
}
