//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Dal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_Comment_HistoryTable
    {
        public int Id { get; set; }
        public Nullable<int> UserUID { get; set; }
        public Nullable<int> MailId { get; set; }
        public Nullable<int> WorkflowType { get; set; }
        public string Comments { get; set; }
        public string CommentedUser { get; set; }
        public string ToUser { get; set; }
    }
}
